server:
  port: 8080
  servlet:
    context-path: /ddd

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ddd_db
    data-username: sa
    data-password:
    data: classpath:db/bank.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update